version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - run:
        name: check links
        command: npx broken-link-checker http://learn.madetech.com --exclude microsoft --exclude linkedin.com --exclude codewars.com -ro  
workflows:
  version: 2
  weekly_checks:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
                - add_link_checker
    jobs:
      - check_links
