version: 2
jobs:
  check_links:
    docker:
      - image: circleci/node:lts
    steps:
      - run:
        name: check links
        command: npx broken-link-checker http://learn.madetech.com --exclude microsoft --exclude 'ext/linkedin' --exclude codewars.com -ro  
workflows:
  version: 2
  on_commit:
    jobs:
      - check_links:
          filters:
            branches:
              only: add_link_checker
  weekly_checks:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - check_links
